name: Deploy BASE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy para EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/base

            git pull

            docker stop app-base || true
            docker rm app-base || true

            docker build -t base:latest .

            docker run -d \
              --name app-base \
              -p 9000:9000 \
              --restart unless-stopped \
              base:latest
